# syntax = docker/dockerfile:1.1-experimental
FROM 192.168.200.51/spiders/jay-requirements:latest
ARG spider
RUN mkdir /app
WORKDIR /app
RUN mkdir -p -m 0600 ~/.ssh && ssh-keyscan github.com >> ~/.ssh/known_hosts
RUN --mount=type=ssh git clone --recursive git@github.com:jinanlongen/jay-${spider}.git /app


RUN rm -f /etc/localtime \
&& ln -sv /usr/share/zoneinfo/Asia/Shanghai /etc/localtime \
&& echo "Asia/Shanghai" > /etc/timezone \

CMD ["bash", "run.sh"]